version: '2.3'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: ${APP_NAME}/app
    volumes:
     - ../:/var/www/html:cached
    networks:
     - sdnet
    ports:
     - "${APP_PORT}:80"
    stdin_open: true
    tty: true   
  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: ${APP_NAME}/node
    volumes:
     - ../:/var/www/html
    networks:
     - sdnet
    ports:
      - 2083:2083
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: ${APP_NAME}/mysql
    volumes:
     - mysqldata:/var/lib/mysql:cached
    networks:
     - sdnet
    ports:
     - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"   
  redis:
    image: redis:alpine
    volumes:
     - redisdata:/data
    networks:
     - sdnet
networks:
  sdnet:
    driver: "bridge"
volumes:
  mysqldata:
    driver: "local"
  redisdata:
    driver: "local"