SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

CREATE DATABASE IF NOT EXISTS `catchtest` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `catchtest`;

CREATE TABLE `customers` (
  `id` int(4) NOT NULL,
  `fName` varbinary(255) NOT NULL,
  `lName` varbinary(255) NOT NULL,
  `email` varbinary(255) NOT NULL,
  `gender` tinyint(1) NOT NULL,
  `ipAdd` varchar(15) NOT NULL,
  `company` varchar(255) NOT NULL,
  `city` varbinary(255) NOT NULL,
  `title` varchar(255) NOT NULL,
  `website` varchar(255) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;


ALTER TABLE `customers`
  ADD PRIMARY KEY (`id`);


ALTER TABLE `customers`
  MODIFY `id` int(4) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7533;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
